name: Generate UML Diagrams
on:
    push:
        paths:
            - '**.puml'
jobs:
    ci:
        runs-on: ubuntu-latest
        env:
            UML_FILES: ".puml"
        steps:
            -   name: Checkout Source
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: ts-graphviz/setup-graphviz@v1
            -   name: Get changed UML files
                id: getfile
                run: |
                    echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep '.puml' | xargs)"
            -   name: UML files considered echo output
                run: |
                    echo ${{ steps.getfile.outputs.files }}
            -   run: wget --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
            -   run: java -jar plantuml.jar -v -tsvg ${{ steps.getfile.outputs.files }}
            -   uses: EndBug/add-and-commit@v7
                with:
                    message: 'Generate SVG for PlantUML'
                    add: '*.svg'
                    push: false
            -   name: Push Changes
                uses: stefanzweifel/git-auto-commit-action@v4.1.2
                with:
                    commit_user_name: "UML Bot"
                    commit_user_email: "uml@bot.alexander.dk"
                    commit_author: "UML Bot <uml@bot.alexander.dk>"
                    commit_message: "Generate SVG and PNG images for UML diagrams"
                    branch: ${{ github.head_ref }}